[tool.poetry]
name = "folio-setae-api"
version = "0.4.0"
description = "API middleware for FOLIO"
authors = ["Nick Cappadona <cappadona@users.noreply.github.com>", "Joshua Greben <jgreben@stanford.edu>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.133.1"
json2xml = "^6.0.4"
requests = "^2.32.5"
python-dotenv = "^1.2.1"
lxml = "^6.0.2"
httpcore = "^1.0.9"

[tool.poetry.group.dev.dependencies]
mypy = "^1.19.1"
flake8 = "^7.3.0"
black = "^26.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
